/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cfarjane <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/06/05 10:45:14 by cfarjane          #+#    #+#             */
/*   Updated: 2018/08/23 17:53:02 by cfarjane         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "./includes/ft_printf.h"
//#include "libft.h"
#include <stdio.h>
#include <locale.h>

#define COLOR "\033[1;33m"
#define NEW "\033[32m"
#define END "\033[0m"
#define RED "\033[31m"

int		main(void)
{
	int ret;
/*	void	*p;
	wchar_t	s1[4];
	wchar_t	s2[4];
	wchar_t	s3[4];
	wchar_t	s4[4];
	wchar_t	s5[4];
	wchar_t	s6[4];
	setlocale(LC_ALL, "");
	s1[0] = 0x53;
	s1[1] = 0x3abc;
	s1[2] = 0x81000;
	s1[3] = '\0';
	s2[0] = 'a';
	s2[1] = 254;
	s2[2] = 'b';
	s2[3] = '\0';
	s3[0] = 254;
	s3[1] = 256;
	s3[2] = 'b';
	s3[3] = '\0';
	s4[0] = 0x53;
	s4[1] = 0x3abc;
	s4[2] = 0x81000;
	s4[3] = '\0';
	s5[0] = 0x53;
	s5[1] = 0x3abc;
	s5[2] = 0x81000;
	s5[3] = '\0';
	s6[0] = 'a';
	s6[1] = 250;
	s6[2] = 'b';
	s6[3] = '\0';
	p = "bonjour";

	printf("%s%s%s\n", COLOR, "-------OKAY------", END);
	ret = ft_printf("%lc", 254);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%lc", 254);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine 2 : %C", 256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real 2 : %C", 256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine 3 : %C", 0xbffe);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real 3 : %C", 0xbffe);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');

	ret = ft_printf("%.2i", -12);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%.2i", -12);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%.2i", 12);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%.2i", 12);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%08d", -124);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%08d", -124);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%08d", 124);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%08d", 124);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%i", 125);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%i", 125);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%lc", 256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%lc", 256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%S", s1);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%S", s1);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%S", s2);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%S", s2);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%S", s3);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%S", s3);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%5S", s4);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%5S", s4);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-12S", s5);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-12S", s5);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%4S", s6);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%4S", s6);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%x", 4294967296);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%x", 4294967296);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%X", 4294967296);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%X", 4294967296);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%hhX", 4294967296);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%hhX", 4294967296);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%lld", -9223372036854775808);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%lld", -9223372036854775808);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%jd", -9223372036854775808);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%jd", -9223372036854775808);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');

	ret = ft_printf("% 10.5d", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("% 10.5d", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%#08x", 42);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%#08x", 42);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%.24o\n", 12012);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%.24o\n", 12012);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%08u\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%08u\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("t%04.2o%#2oet %#-8.3o titi\n", 0, 0, 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("t%04.2o%#2oet %#-8.3o titi\n", 0, 0, 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%0+5d", 42);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%0+5d", 42);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-10.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-10.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-+10.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-+10.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%+10.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%+10.5d!", 4242);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%00+10.4d!", 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%00+10.4d!", 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%#-8.3o!", 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%#-8.3o!", 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%011X", 0xdd66);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%011X", 0xdd66);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%011x", 0xdd66);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%011x", 0xdd66);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%5.2s is a string", "this");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%5.2s is a string", "this");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-5.2s is a string", "this");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-5.2s is a string", "this");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-5.2s is a string", "");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-5.2s is a string", "");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-6.8s!", "12345");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-6.8s!", "12345");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-8s!", "coco");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-8s!", "coco");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-2s!", "");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-2s!", "");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-2.4s!", NULL);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-2.4s!", NULL);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');

	printf("%s%s%s\n", COLOR, "-------KO------", END);
	printf("%s%s%s\n", RED, "conv d", END);
	ret = ft_printf("@moulitest: %.d %.0d", -42, 43);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %.d %.0d", -42, 43);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %+.d %+.0d", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %+.d %+.0d", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %5.d! %5.0d!", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %5.d! %5.0d!", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	printf("%s%s%s\n", RED, "conv x", END);
	ret = ft_printf("@moulitest: %#.x %#.0x", 42, 43);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %#.x %#.0x", 42, 43);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %#.x %#.0x", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %#.x %#.0x", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %.x %.0x", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %.x %.0x", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %5.x! %5.0x!", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %5.x! %5.0x!", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	printf("%s%s%s\n", RED, "conv o", END);
	ret = ft_printf("@moulitest: %.o %.0o", 42, 43);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %.o %.0o", 42, 43);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %#.o %#.0o", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %#.o %#.0o", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %.o %.0o", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %.o %.0o", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@moulitest: %5.o! %5.0o!", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@moulitest: %5.o! %5.0o!", 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%.0s", "hi");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%.0s", "hi");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%.0s!", "toto");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%.0s!", "toto");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%4.2ss! ", "coco");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%4.2ss! ", "coco");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%.0c! ", 'a');
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%.0c! ", 'a');
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("u%4.2ss %-1.s!\n %---5.3s! ", "coco", NULL, "yooo");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("u%4.2ss %-1.s!\n %---5.3s! ", "coco", NULL, "yooo");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%#.3x", 12);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%#.3x", 12);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%0#14.0o", 14256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%0#14.0o", 14256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%0#10.0x!", 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%0#10.0x!", 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%0#10.0x %0#x", 12345, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%0#10.0x %0#x", 12345, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("toto%.0d et %+.i et  %   .0D !!!", 0, 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("toto%.0d et %+.i et  %   .0D !!!", 0, 0, 0);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%%%", "test");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%%%", "test");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("@main_ftprintf: %####0000 33..1d", 256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("@main_ftprintf: %####0000 33..1d", 256);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%zj", 9223372036854775807);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%zj", 9223372036854775807);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("%-5+d", -42);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("%-5+d", -42);
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("% Z");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("% Z");
	printf("\n%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", COLOR, "-------MINUS------", END);
	ret = ft_printf("mine : %08u!\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %08u!\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %8.6s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %8.6s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %-ds\n", 125);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %-ds\n", 125);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %-5ds\n",25);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %-5ds\n", 25);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("hello ca%----4c %1c va %10c%-c ??\n", '\0', '\n', (char)564, 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("hello ca%----4c %1c va %10c%-c ??\n", '\0', '\n', (char)564, 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %----4c\n", '\0');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %----4c\n", '\0');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %1c\n", '\n');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %1c\n", '\n');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %10c\n", (char)564);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %10c\n", (char)564);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %-c\n", (char)564);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %-c\n", (char)564);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %08u\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %08u\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %8o\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %8o\n", 171894);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", COLOR, "-------ZERO------", END);
	ret = ft_printf("mine : %.0d\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.0d\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
`	ret = ft_printf("mine : %.0o\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.0o\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.0u\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0u\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.0x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.0x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %0d\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0d\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %0o\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0o\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %0u\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0u\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %0x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %5s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %5s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", COLOR, "-------WIDTH------", END);
	ret = ft_printf("mine : %50d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %50d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %22d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %22d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %36d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %36d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %120d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %120d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %13d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %13d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %14d\n", -256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %14d\n", -256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", COLOR, "-------PREC------", END);
	ret = ft_printf("mine : %.2d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.2d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.2d\n", -254);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.2d\n", -254);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.4d\n", 125);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.4d\n", 125);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.5d\n", 12);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.5d\n", 12);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", COLOR, "-------BOTH------", END);
	ret = ft_printf("mine : %8.2d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %8.2d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %9.6d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %9.6d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %5.3d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %5.3d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %9.12d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %9.12d\n", 256);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", COLOR, "-------STRING------", END);
	ret = ft_printf("mine : %.5d\n", -461);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.5d\n", -461);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %0i\n", -519);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0i\n", -519);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.5d\n", 461);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.5d\n", 461);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.d\n", 2);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.d\n", 2);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %010s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %010s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.2s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.2s\n", "toto");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------CHAR------", END);
	ret = ft_printf("mine : %C\n", 0xffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %C truc %d\n", 0xffff, 5);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %C\n", 0x4e6);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %C\n", 0x4e6);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %C\n", 0x11ffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %C\n", 0x11ffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %C\n", 0x11ffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %C\n", 0x11ffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %10c\n", 'c');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %10c\n", 'c');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %5c\n", 'b');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %5c\n", 'b');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %1c\n", 'a');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %1c\n", 'a');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.1c\n", 'c');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = ft_printf("real : %.1c\n", 'c');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------NULL------", END);
	ret = ft_printf("mine : %s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.11s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.11s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.2s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.2s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %8s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %8s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %2s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %2s\n", NULL);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------DECIMAL------", END);
	printf("%s%s%s\n", RED, "NORMAL", END);
	ret = ft_printf("mine : %d\n", 2360);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %d\n", 2360);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ld\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ld\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %D\n", 2147483647);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %D\n", 2147483647);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lld\n", (long long)9223372036854775805);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lld\n", (long long)9223372036854775805);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hd\n", (short)32767);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hd\n", (short)32767);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhd\n", (char)315);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhd\n", (char)315);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jd\n", (intmax_t)9223372036854775805);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jd\n", (intmax_t)9223372036854775805);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zd\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zd\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "INTMAX", END);
	ret = ft_printf("mine : %d\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %d\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ld\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ld\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lld\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lld\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %D\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %D\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hd\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hd\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhd\n", (char)235);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhd\n", (char)235);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jd \n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jd\n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zd\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zd\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "NEGATIF", END);
	ret = ft_printf("mine : %d\n", -2360);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %d\n", -2360);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ld\n", -2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ld\n", -2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %D\n", -2147483647);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %D\n", -2147483647);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lld\n", (long long)-9223372036854775807);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lld\n", (long long)-9223372036854775807);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hd\n", (short)-32767);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hd\n", (short)-32767);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhd\n", (char)-97);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhd\n", (char)-97);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jd \n", (intmax_t)-9223372036854775807);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jd\n", (intmax_t)-9223372036854775807);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zd\n", (long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zd\n", (long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
*/
	printf("\n%s%s%s\n", COLOR, "------UNICODE------", END);
	ret = ft_printf("mine : %ls\n", L'œ');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = ft_printf("real : %ls\n", L'œ');
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ls\n", L"このページでは、文字のリストについて説明します。");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = ft_printf("real : %ls\n", L"このページでは、文字のリストについて説明します。");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ls\n", 0x11ffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = ft_printf("real : %ls\n", 0x11ffff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ls\n", 12335486662);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = ft_printf("real : %ls\n", 12335486662);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ls\n", -42);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = ft_printf("real : %ls\n", -42);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
/*
	printf("\n%s%s%s\n", COLOR, "------HEXA------", END);
	printf("%s%s%s\n", RED, "options", END);
	ret = ft_printf("mine : %12x\n", -6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %12x\n", -6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %#x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %#x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %012x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %012x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.0x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.0x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	printf("%s%s%s\n", RED, "precision", END);
	ret = ft_printf("mine : %9.25x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %9.25x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %3.12x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %3.12x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	printf("%s%s%s\n", RED, "width", END);
	ret = ft_printf("mine : %9x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %9x\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %12x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %12x\n", 6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("%s%s%s\n", RED, "NORMAL", END);
	ret = ft_printf("mine : %lx\n", (unsigned long)2147483648);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lx\n", (unsigned long)2147483648);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %X\n", (unsigned int)2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %X\n", (unsigned int)2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hx\n", (unsigned short)2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hx\n", (unsigned short)2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhx\n", (unsigned char)21474836);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhx\n", (unsigned char)21474836);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jx\n", (uintmax_t)6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jx\n", (uintmax_t)6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zx\n", (size_t)12596);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zx\n", (size_t)12596);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "NEGATIF", END);
	ret = ft_printf("mine : %lx\n", (unsigned long)-2147483648);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lx\n", (unsigned long)-2147483648);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %X\n", (unsigned int)-2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %X\n", (unsigned int)-2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hx\n", (unsigned short)-2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hx\n", (unsigned short)-2147483750);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhx\n", (unsigned char)-21474836);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhx\n", (unsigned char)-21474836);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jx\n", (uintmax_t)-6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jx\n", (uintmax_t)-6542826);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zx\n", (size_t)-12596);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zx\n", (size_t)-12596);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "INTMAX", END);
	ret = ft_printf("mine : %x\n", 2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %x\n", 2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lx\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lx\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llx\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llx\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %X\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %X\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hx\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hx\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhx\n", (char)128);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhx\n", (char)128);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jx \n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jx\n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zx\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zx\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------OCTAL------", END);
	printf("\n%s%s%s\n", RED, "NORMAL", END);
	ret = ft_printf("mine : %lo\n", (unsigned long)258);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lo\n", (unsigned long)258);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llo\n", (unsigned long long)127);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llo\n", (unsigned long long)127);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ho\n", (unsigned short)1475);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ho\n", (unsigned short)1475);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hho\n", (unsigned char)12);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hho\n", (unsigned char)12);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jo\n", (uintmax_t)14785000);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jo\n", (uintmax_t)14785000);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zo\n", 0xffff14785aa);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zo\n", 0xffff14785aa);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "NEGATIF", END);
	ret = ft_printf("mine : %lo\n", (unsigned long)-258);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lo\n", (unsigned long)-258);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llo\n", (unsigned long long)-127);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llo\n", (unsigned long long)-127);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ho\n", (unsigned short)-1475);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ho\n", (unsigned short)-1475);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hho\n", (unsigned char)-12);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hho\n", (unsigned char)-12);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jo\n", (uintmax_t)-14785000);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jo\n", (uintmax_t)-14785000);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zo\n", -0xffff14785aa);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zo\n", -0xffff14785aa);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "MAXIMUM", END);
	ret = ft_printf("mine : %o\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %o\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lo\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lo\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llo\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llo\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %O\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %O\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ho\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ho\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hho\n", (char)235);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hho\n", (char)235);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %jo\n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %jo\n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zo\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zo\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	ft_putchar('\n');
	ret = ft_printf("mine : %o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %#.4o\n", -2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %#.4o\n", -2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %#o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %#o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %#o\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %#o\n", 0);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.9o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.9o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.21o\n", -2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.21o\n", -2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %15o\n", -21);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %15o\n", -21);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %12o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %12o\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------UNSIGNED------", END);
	printf("\n%s%s%s\n", RED, "NORMAL", END);
	ret = ft_printf("mine : %u\n", 2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %u\n", 2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lu\n", (unsigned long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lu\n", (unsigned long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llu\n", (unsigned long long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llu\n", (unsigned long long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hu\n", (unsigned char)2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhu\n", (unsigned char)2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhu\n", (unsigned char)100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhu\n", (unsigned char)100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ju\n", (unsigned long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ju\n", (unsigned long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zu\n", (unsigned long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zu\n", (unsigned long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "NEGATIF", END);
	ret = ft_printf("mine : %lu\n", (unsigned long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lu\n", (unsigned long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llu\n", (unsigned long long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llu\n", (unsigned long long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hu\n", (unsigned char)-2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhu\n", (unsigned char)-2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhu\n", (unsigned char)-100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhu\n", (unsigned char)-100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ju\n", (unsigned long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ju\n", (unsigned long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zu\n", (unsigned long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zu\n", (unsigned long)-2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", RED, "MAXIMUM", END);
	ret = ft_printf("mine : %u\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %u\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %lu\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %lu\n", 0x44ff551100);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %llu\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %llu\n", (long long)0x11ff11ff11ff11ff);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %U\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %U\n", (int)0xff11ff11ff88);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hu\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hu\n", (short)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %hhu\n", (char)235);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %hhu\n", (char)235);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ju\n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ju\n", (intmax_t)0x1789);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %zu\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %zu\n", (long)2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	ft_putchar('\n');
	ret = ft_printf("mine : %-u\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %-u\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %0u\n", -2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %0u\n", -2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.12u\n", -2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.12u\n", -2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.9u\n", (unsigned int)-2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.9u\n", (unsigned int)-2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.12u\n", -2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.12u\n", -2147);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %3u\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %3u\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %21u\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %21u\n", 2147483);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------SUPERIOR------", END);
	ret = ft_printf("mine : %ld\n", -2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ld\n", -2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %ld\n", 2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %ld\n", 2147483650);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);

	printf("\n%s%s%s\n", COLOR, "------PERCENT------", END);
	ret = ft_printf("mine : %.0%\n", -10);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.0%\n", -10);
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %02%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %02%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.1%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.1%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %017%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %017%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.10%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.10%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.9%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.9%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ft_putchar('\n');
	ret = ft_printf("mine : %.1%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);
	ret = printf("real : %.1%\n");
	printf("%s%s%d%s\n", NEW, "ret = ", ret, END);*/
	return (0);
}
